// flow-typed signature: e68509bba7244f75693e35f6d286ee81
// flow-typed version: <<STUB>>/eslint-plugin-require-path-exists_v^1.1.9/flow_v0.140.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-require-path-exists'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-require-path-exists' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-require-path-exists/lib/exists' {
  declare module.exports: any;
}

declare module 'eslint-plugin-require-path-exists/lib' {
  declare module.exports: any;
}

declare module 'eslint-plugin-require-path-exists/lib/notEmpty' {
  declare module.exports: any;
}

declare module 'eslint-plugin-require-path-exists/lib/tooManyArguments' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-require-path-exists/index' {
  declare module.exports: $Exports<'eslint-plugin-require-path-exists'>;
}
declare module 'eslint-plugin-require-path-exists/index.js' {
  declare module.exports: $Exports<'eslint-plugin-require-path-exists'>;
}
declare module 'eslint-plugin-require-path-exists/lib/exists.js' {
  declare module.exports: $Exports<'eslint-plugin-require-path-exists/lib/exists'>;
}
declare module 'eslint-plugin-require-path-exists/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-require-path-exists/lib'>;
}
declare module 'eslint-plugin-require-path-exists/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-require-path-exists/lib'>;
}
declare module 'eslint-plugin-require-path-exists/lib/notEmpty.js' {
  declare module.exports: $Exports<'eslint-plugin-require-path-exists/lib/notEmpty'>;
}
declare module 'eslint-plugin-require-path-exists/lib/tooManyArguments.js' {
  declare module.exports: $Exports<'eslint-plugin-require-path-exists/lib/tooManyArguments'>;
}
